name: darternator
description: A Dart API
version: 0.0.2
homepage: https://github.com/darylrue/Darternator
author: Daryl Rue <kinematicweb@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
